/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ACompareComparison extends PComparison
{
    private PArithExp _left_;
    private TLess _less_;
    private PArithExp _right_;

    public ACompareComparison()
    {
        // Constructor
    }

    public ACompareComparison(
        @SuppressWarnings("hiding") PArithExp _left_,
        @SuppressWarnings("hiding") TLess _less_,
        @SuppressWarnings("hiding") PArithExp _right_)
    {
        // Constructor
        setLeft(_left_);

        setLess(_less_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new ACompareComparison(
            cloneNode(this._left_),
            cloneNode(this._less_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACompareComparison(this);
    }

    public PArithExp getLeft()
    {
        return this._left_;
    }

    public void setLeft(PArithExp node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TLess getLess()
    {
        return this._less_;
    }

    public void setLess(TLess node)
    {
        if(this._less_ != null)
        {
            this._less_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._less_ = node;
    }

    public PArithExp getRight()
    {
        return this._right_;
    }

    public void setRight(PArithExp node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._less_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._less_ == child)
        {
            this._less_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PArithExp) newChild);
            return;
        }

        if(this._less_ == oldChild)
        {
            setLess((TLess) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PArithExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
