/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AExpsExpList extends PExpList
{
    private PExp _exp_;
    private PExpRest _expRest_;

    public AExpsExpList()
    {
        // Constructor
    }

    public AExpsExpList(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") PExpRest _expRest_)
    {
        // Constructor
        setExp(_exp_);

        setExpRest(_expRest_);

    }

    @Override
    public Object clone()
    {
        return new AExpsExpList(
            cloneNode(this._exp_),
            cloneNode(this._expRest_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpsExpList(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PExpRest getExpRest()
    {
        return this._expRest_;
    }

    public void setExpRest(PExpRest node)
    {
        if(this._expRest_ != null)
        {
            this._expRest_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expRest_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._expRest_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._expRest_ == child)
        {
            this._expRest_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._expRest_ == oldChild)
        {
            setExpRest((PExpRest) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
