/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ANonemptyFormalList extends PFormalList
{
    private PType _type_;
    private TId _id_;
    private PFormalRest _formalRest_;

    public ANonemptyFormalList()
    {
        // Constructor
    }

    public ANonemptyFormalList(
        @SuppressWarnings("hiding") PType _type_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PFormalRest _formalRest_)
    {
        // Constructor
        setType(_type_);

        setId(_id_);

        setFormalRest(_formalRest_);

    }

    @Override
    public Object clone()
    {
        return new ANonemptyFormalList(
            cloneNode(this._type_),
            cloneNode(this._id_),
            cloneNode(this._formalRest_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANonemptyFormalList(this);
    }

    public PType getType()
    {
        return this._type_;
    }

    public void setType(PType node)
    {
        if(this._type_ != null)
        {
            this._type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PFormalRest getFormalRest()
    {
        return this._formalRest_;
    }

    public void setFormalRest(PFormalRest node)
    {
        if(this._formalRest_ != null)
        {
            this._formalRest_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._formalRest_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._type_)
            + toString(this._id_)
            + toString(this._formalRest_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._type_ == child)
        {
            this._type_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._formalRest_ == child)
        {
            this._formalRest_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._formalRest_ == oldChild)
        {
            setFormalRest((PFormalRest) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
